# Generated by Django 5.2.13 on 2026-04-08 08:39

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0002_remove_fileai_node_remove_fileembedding_file_ai_and_more'),
    ]

    operations = [
        CreateExtension('vector'),
        migrations.CreateModel(
            name='DocumentParseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parser_name', models.CharField(default='docling', max_length=64)),
                ('parser_mode', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32)),
                ('input_format', models.CharField(blank=True, max_length=32)),
                ('input_document_hash', models.CharField(blank=True, max_length=64)),
                ('input_page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('result_page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('timings', models.JSONField(blank=True, default=dict)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parse_result', to='files.node')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('token_count', models.PositiveIntegerField(blank=True, null=True)),
                ('section_title', models.CharField(blank=True, max_length=255)),
                ('page_from', models.PositiveIntegerField(blank=True, null=True)),
                ('page_to', models.PositiveIntegerField(blank=True, null=True)),
                ('chunk_meta', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32)),
                ('error_message', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parse_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='document_ai.documentparseresult')),
            ],
            options={
                'ordering': ['chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='ChunkEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='BAAI/bge-m3', max_length=128)),
                ('model_version', models.CharField(blank=True, max_length=32)),
                ('vector', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('embedded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='document_ai.documentchunk')),
            ],
            options={
                'indexes': [models.Index(fields=['model_name'], name='document_ai_model_n_3ebeeb_idx'), pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['vector'], m=16, name='chunk_embedding_vector_hnsw_idx', opclasses=['vector_cosine_ops'])],
                'constraints': [models.UniqueConstraint(fields=('chunk', 'model_name', 'model_version'), name='uniq_embedding_per_chunk_model_version')],
            },
        ),
        migrations.AddIndex(
            model_name='documentparseresult',
            index=models.Index(fields=['status'], name='document_ai_status_2b6457_idx'),
        ),
        migrations.AddIndex(
            model_name='documentparseresult',
            index=models.Index(fields=['parser_name'], name='document_ai_parser__bff5ef_idx'),
        ),
        migrations.AddIndex(
            model_name='documentparseresult',
            index=models.Index(fields=['input_document_hash'], name='document_ai_input_d_af555b_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['parse_result', 'chunk_index'], name='document_ai_parse_r_6d5c6d_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentchunk',
            constraint=models.UniqueConstraint(fields=('parse_result', 'chunk_index'), name='uniq_chunk_index_per_parse_result'),
        ),
    ]
