# Generated by Django 5.2.14 on 2026-05-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_ai', '0002_chunkembedding_sparse_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
