# Generated by Django 5.2.14 on 2026-05-16 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_ai', '0005_searchjob'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='searchjob',
            new_name='document_ai_owner_i_f2d395_idx',
            old_name='document_ai_owner_i_34b3e2_idx',
        ),
    ]
