# Generated by Django 5.2.14 on 2026-05-21 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_ai', '0008_ragjob'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ragjob',
            new_name='document_ai_owner_i_20a6ea_idx',
            old_name='document_ai_owner_i_92a1b8_idx',
        ),
    ]
