# Generated by Django 5.2.14 on 2026-05-27 06:27

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_ai', '0009_rename_document_ai_owner_i_92a1b8_idx_document_ai_owner_i_20a6ea_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentparseresult',
            name='auto_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='documentparseresult',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='ChunkSentenceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('token_count', models.PositiveIntegerField(blank=True, null=True)),
                ('vector', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ('sparse_vector', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_embeddings', to='document_ai.documentchunk')),
            ],
            options={
                'indexes': [models.Index(fields=['chunk', 'sentence_index'], name='document_ai_chunk_i_8971ec_idx'), pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['vector'], m=16, name='sent_emb_vec_hnsw_idx', opclasses=['vector_cosine_ops'])],
                'constraints': [models.UniqueConstraint(fields=('chunk', 'sentence_index'), name='uniq_sentence_emb_per_chunk_index')],
            },
        ),
    ]
