# Generated by Codex on 2026-05-28

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_ai", "0010_documentparseresult_auto_tags_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChunkSegmentEmbedding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("window_size", models.PositiveSmallIntegerField(default=2)),
                ("segment_index", models.PositiveIntegerField()),
                ("text", models.TextField()),
                ("char_start", models.PositiveIntegerField(default=0)),
                ("char_end", models.PositiveIntegerField(default=0)),
                ("vector", pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ("sparse_vector", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segment_embeddings",
                        to="document_ai.documentchunk",
                    ),
                ),
            ],
            options={
                "ordering": ["chunk", "window_size", "segment_index"],
                "indexes": [
                    models.Index(fields=["chunk", "window_size", "segment_index"], name="document_ai_chunk_i_41e103_idx"),
                    models.Index(fields=["last_used_at"], name="document_ai_last_us_0334c7_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chunk", "window_size", "segment_index"),
                        name="uniq_segment_emb_per_chunk_window_index",
                    )
                ],
            },
        ),
    ]
