# Generated by Django 5.2.16 on 2026-08-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_ai', '0020_embedding_generations'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='performance_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='documentparseresult',
            name='performance_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
