# Generated by Django 5.2.16 on 2026-08-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_ai', '0021_documentchunk_performance_metrics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(db_index=True, max_length=64)),
                ('cpu_percent', models.FloatField(blank=True, null=True)),
                ('mem_mb', models.FloatField(blank=True, null=True)),
                ('gpu_mem_mb', models.FloatField(blank=True, null=True)),
                ('db_connections', models.PositiveIntegerField(blank=True, null=True)),
                ('disk_free_mb', models.FloatField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['service', '-collected_at'], name='document_ai_service_0e6b10_idx')],
            },
        ),
    ]
