# Generated by Django 5.2.16 on 2026-09-10 08:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_ai', '0026_lean_embedding_contract'),
        ('workspaces', '0008_merge_quality_profile_axes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ragjob',
            index=models.Index(fields=['workspace', 'owner', 'status', '-completed_at'], name='docai_rag_ws_own_st_cmp_idx'),
        ),
        migrations.AddIndex(
            model_name='ragjob',
            index=models.Index(fields=['workspace', 'owner', '-created_at'], name='docai_rag_ws_own_created_idx'),
        ),
    ]
