server {
    listen 80;
    server_name _; # 실제 배포 시에는 example.com 과 같이 도메인 이름으로 변경해야 합니다.

    server_tokens off;
    client_max_body_size 200m;

    # 정적 파일 제공 (Django collectstatic 결과물)
    location /static/ {
        alias /var/www/staticfiles/;
        access_log off;
        expires 30d;
    }

    # 내부 테스트용 미디어 파일 (필요시 사용, 또는 권한 검사 등)
    location /internal-test/ {
        internal;
        alias /var/www/uploads/;
    }

    # 백엔드 프록시
    location / {
        proxy_pass http://app:8000;

        # Request CORS Header
        proxy_set_header Host $http_host;

        # Response CORS Header
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
