server {
    listen 80;
    server_name _;

    client_max_body_size 200m;

    location / {
        proxy_pass http://app:8000;

        # Request CORS Header
        proxy_set_header Host $http_host;

        # Response CORS Header
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /internal-test/ {
        internal; # 직접 접속 시 404가 떠야 정상
        alias /var/www/uploads/;
    }
}
