# Generated by Django 5.2.13 on 2026-04-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_remove_fileai_node_remove_fileembedding_file_ai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstorage',
            name='total_size',
            field=models.BigIntegerField(default=1073741824),
        ),
    ]
