# Generated by Django 5.2.14 on 2026-05-29 08:20

from django.db import migrations, models


def disable_ai_for_trashed_nodes(apps, schema_editor):
    Node = apps.get_model("files", "Node")
    Node.objects.filter(trashed=True).update(ai_processing_enabled=False)


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_alter_userstorage_total_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="ai_processing_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(disable_ai_for_trashed_nodes, migrations.RunPython.noop),
    ]
