# Generated by Django 5.2.16 on 2026-08-26 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_node_ai_processing_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('upload', 'Upload'), ('rename', 'Rename'), ('move', 'Move'), ('delete', 'Delete'), ('restore', 'Restore'), ('permanent_delete', 'Permanent delete'), ('empty_trash', 'Empty trash')], db_index=True, max_length=32)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='completed', max_length=32)),
                ('error_message', models.TextField(blank=True)),
                ('performance_metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to='files.node')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_operation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='files_fileo_owner_i_b7efb5_idx'), models.Index(fields=['operation', '-created_at'], name='files_fileo_operati_e3268f_idx')],
            },
        ),
    ]
