name: Pytest Unit

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare env file
        run: cp .env.example .env.dev

      - name: Build test image
        run: docker compose -f docker-compose.dev.yml build celery-core-worker

      - name: Run unit tests
        run: docker compose -f docker-compose.dev.yml run --rm celery-core-worker python -m pytest -m "unit"

      - name: Cleanup
        if: always()
        run: docker compose -f docker-compose.dev.yml down -v --remove-orphans
